org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.4
loader_version=0.16.9
yarn_mappings=1.21.4+build.8
loom_version=1.9-SNAPSHOT
fabric_kotlin_version=1.13.9+kotlin.2.3.10

mod_version=1.0.1-alpha.6+MC-1.21.4
maven_group=dev.superficialcake.dankhelper
archives_base_name=dankhelper

# Dependencies
fabric_api_version=0.119.3+1.21.4
cloth_config_version=17.0.144
mod_menu_version=13.0.3